BrightspaceHypermediaComponents/foundation-engine

- state/HypermediaState.js
- state/sirenComponents/SirenAction.js
- state/sirenComponents/SirenClasses.js
- state/sirenComponents/SirenEntity.js
- state/sirenComponents/SirenLink.js
- state/sirenComponents/SirenProperty.js
- state/sirenComponents/SirenSubEntities.js
- state/sirenComponents/SirenSubEntity.js
- Renames `deleteComponent` to `delete` for all sirenComponents (to become `Observables`)
- Adds delete function to `SirenSubEntity`
- Manually tested with `polarisdev` sitelord instance and local BSI
> Fixing "sirenComponent.delete is not a function"

- .editorconfig
- state/Fetchable.js
- state/HypermediaState.js
- state/observable/SirenAction.js
- state/store.js
- test/Fetchable.test.js
[US121368](https://rally1.rallydev.com/#/detail/userstory/441183090652?fdp=true): Creation of Fetchable mixin
[Architecture Design](https://desire2learn.atlassian.net/wiki/spaces/POL/pages/1622278478/US120980+Defining+the+architecture+of+hmc-foundation)
Adds the `Fetchable` mixin which functions as an abstract class for use with the in progress `fetch` method.
- `fetchStatus` is now an object attached to the `Fetchable` with `start()`, `cancel()`, and `done()` methods
- `observable/SirenAction` and `HypermediaState` both implement `Fetchable`
- `href(input)` method converted to `setQueryParams` method
- `header()` method converted to `headers` getter
- Snuck a `.editorconfig` file in there because it was causing problems not having one
- added new unit tests for `FetchStatus`
- added …
> Fetchable mixin

- .eslintrc.json
- .gitignore
- package.json
- test/.eslintrc.json
[US121576](https://rally1.rallydev.com/#/detail/userstory/447027030140?fdp=true)
Fun fact: `open-wc/testing-karma` comes with `istanbul` coverage built in. You just have to pass a flag.
As expected, our code coverage sucks right now, but now we can measure how badly it sucks 🥇
> test: Added coverage configuration

- state/observable/ObserverMap.js
- state/observable/SirenAction.js
- state/observable/SirenLink.js
- state/observable/SirenSubEntity.js
- test/observerMap.test.js
[Story](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?Iteration=%2Fiteration%2F357252967044&Name=&Project=%2Fproject%2F357252966636&Release=u&cpoid=357252966636&detail=%2Fuserstory%2F460347083068&rankScope=%2Fiteration%2F357252967044&rankTo=BOTTOM&typeDef=7362609683)
Method allows for consistent merging of observerMaps and eases testing. Yay.
> Add merge method to ObserverMap

- state/observable/SirenSubEntities.js
- state/observable/SirenSubEntity.js
- test/observable/sirenSubEntities.test.js
- test/observable/sirenSubEntity.test.js
[US122956](https://rally1.rallydev.com/#/detail/userstory/460074259704?fdp=true)
The `observableTypes.subEntity` and`observableTypes.subEntities` now reflect a value that is an object. For now, this is the siren entity object parsed from `siren-parser`. This gives the developer creating a component access to the subEntities' links, properties, etc. In the future, this will be a friendly facade that will be easy to interact with when building foundation components.
Before, the value of a subEntity and the subEntities array reflected only the `href`. This was problematic for both selfless entities and was also non-intuitive to work with and read.
Subentities are still indexed by their `self` links, but this will be altered in the future to support selfless entities.
```js
class …
```
> feat: SubEntity and SubEntities observables reflect the siren parsed entity

- state/HypermediaState.js
- test/siren-observables.test.js
Title says it all. Fixed the one set of tests that required it.
> fix: We shouldn't allow HypermediaState to be exported

- state/fetch.js
Basically, what we had before if you `await fetch` the call to onServerResponse may run before or may run after.. This will probably cause a lot of headaches so I've changed it so the promise returned isn't the same promise as `fetchable.fetchStatus` however it should resolve as if it was the same one. This time you can be assured that `onServerResponse` has run and was successful.
This also has the added benefits of people being able to catch errors from `onServerResponse` when calling fetch.
I ran this code through my tests in my other branch. Given the change is complex enough. I decided to switch it off to it's own branch. Also, it seems like it could help the other tests in progress so it will hopefully be merged faster than my test one.
> Update fetch to be more consistent in calls.

- state/observable/README.md
Issue #49 
Adds basic documentation for the different observables. My plan is to add pages for each type with examples, but I wanted to make sure we document `route` and `prime` properly somewhere.
See: https://github.com/BrightspaceHypermediaComponents/foundation-engine/tree/zina/readme/state/observable
I've intentionally not linked this on the main readme because some of the features aren't implemented yet, like subEntity routing. The readme represents what we are building, not necessarily what we have.
> docs: Added readme for observables

- state/HypermediaState.js
- test/state/HypermediaState.test.js
Fixes issue #53 
Wait for the `fetchStatus` on the relevant states instead of for the `mock` to be called.
> test: Fixing not flaky test

- state/observable/SirenFacade.js
- test/data/observable/entities.js
- test/observable/sirenFacade.test.js
[US123074](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F461413871352&fdp=true?fdp=true)
Introduces the `SirenFacade` object, a class designed to be used for reflecting observable Siren entities to components without attaching extraneous information to them. This is the first iteration and has notable items intentionally missing from it.
- Introduces the class, but existing functionality is unchanged. Coming in next PR
- Actions returns just a list of the names of each action. We are still deciding how we want to handle actions attached to subEntities
- new unit tests added, which are modelled after styles I liked from both @tenbradley and @AKobets work
- side note that I think Alex is right and we should start keeping mock data directly in the …
> Added SirenFacade and unit tests

- state/observable/SirenFacade.js
- state/observable/SirenSubEntities.js
- state/observable/SirenSubEntity.js
- state/observable/SirenSummonAction.js
- state/observable/sirenObservableFactory.js
- test/observable/sirenSubEntities.test.js
- test/state/HypermediaState.test.js
[US123074](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F461413871352&fdp=true?fdp=true)
The second and final portion of the `SirenFacade` story connects the new `SirenFacade` class into the following `Observable`s:
- `SirenSubEntity`: now reflects the `SirenFacade` instead of the parsed entity
- `SirenSubEntities`: reflects an Array of `SirenFacade` objects
- `SirenSummonAction`: reflects the same action, but returns a `SirenFacade` on `summon()`
- Added the `rel` property to the `SirenFacade`
- Existing unit tests
> feat: Implement SirenFacade for relevant Observable types

- state/HypermediaState.js
- state/observable/Observable.js
- state/observable/README.md
This was something that was half implemented. It is now fully implemented (by changing like three lines 🤔)
This enables components to update the state without sending an action, like so:
```js
this._state.updateProperties({
items: {
observable: observableTypes.subEntities,
rel: rels.item,
value: newListOfItems
}
});
```
> fix: Add updateProperty to the Observable class

- state/observable/Routable.js
- test/example-components/component-integration.test.js
- test/example-components/summon-action-components.js
Nested summon actions were not working properly. Now they do! Added a test to prove it.
> fix: Fixed routing for nested summon actions

- framework/lit/HypermediaStateMixin.js
The `await` breaks the localizeMixin from core.
> fix: Remove await from the fetch

- state/observable/SirenAction.js
- test/example-components/action-components.js
- test/example-components/component-integration.test.js
- test/observable/sirenAction.test.js
[US122856](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F459739288064&fdp=true?fdp=true)
Engine portion of the story. The new `bulk-update-collection` action takes fields in the form of:
```
inputIds: 1
inputIds: 2
```
Previously, the engine did not support fields with the same name. I've remedied this in this PR. Now, in the component, we do this with an action like so:
```js
this.someAction.commit({
inputIds: [1, 2]
});
```
The engine will automagically unpack it into multiple formData entries.
- New very basic unit tests added for `SirenAction`. None existed before. We should add more.
- Basic integration test for `actions` added
- Cleaned up existing integration tests so they no longer use `aTimeout`
> feat: Added support for array fields

- state/observable/SirenAction.js
Users can create learning paths with empty names and descriptions which are converted to "[Object object]"
This PR commits an empty string instead - it is the component's job to validate.
Tested on `polarisdev2` with local BSI
> fix: Check for undefined instead of committing an object

- framework/lit/HypermediaResult.js
- package.json
- test/example-components/component-integration.test.js
- test/framework/lit/hypermedia-result.test.js
- test/hypermedia-components.test.js
[US124640](https://rally1.rallydev.com/#/357252966636d/dashboard?detail=%2Fuserstory%2F492652604048&fdp=true?fdp=true)
https://github.com/BrightspaceHypermediaComponents/foundation-engine/pull/80
Changes the `matchAll` function within the `HypermediaResults` class to use a `while` loop with the `exec` function to perform regex processing because `matchAll` is not supported in Legacy Edge. This solution was chosen over a polyfill.
**Note:** `exec` was chosen over the `match` function because the global flag is required. `match` will ignore capture groups whenever the global flag is set, where exec does not. See also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#description
New integration tests added to test the functionality of the custom …
> fix: Use while exec instead of matchAll

- helper/deepCopy.js
- test/example-components/component-integration.test.js
- test/example-components/subentities-components.js
- test/helper/deepCopy.test.js
If there was a cycle in objects we were deep copying we would receive a stackover flow. So I fixed it and added tests to deep copy and how we expect things to work.
> fix: Update Deep copy to handle cycles and added tests.

- state/observable/sirenObservableFactory.js
So basically, adding support for custom observable types. So one can observe a property like this:
```
import { W2DSirenClasses } from './w2dDateCategoryObserver.js';
...
// W2DSirenClasses sets an array of classes.
_classes: { type: String, observable: observableTypes.custom, observableObject: W2DSirenClasses, method: (classes) => classes.pop() 
```
Tested on my local machine using a component and custom class.
For testing you can use this branch: https://github.com/BrightspaceHypermediaComponents/foundation-components/tree/maya/customObservableTest
> Add support for custom observable support

- state/observable/README.md
- state/observable/RefreshState.js
- state/observable/sirenObservableFactory.js
This adds a new observable so you can refresh the state. You can use it like this:
```
static get properties() {
return {
...
_isNew: {
type: Boolean,
observable: observableTypes.classes,
method: classes => classes.includes('creating'),
route: [{observable: observableTypes.link, rel: rels.specialization}]
},
_refreshState: {
type: Object,
observable: observableTypes.refreshState,
route: [{observable: observableTypes.link, rel: rels.specialization}]
}
};
}
...
_onCancelClick() {
this._refreshState();
}
```
Boom when you call this._refreshState it will refresh the state following the link `observable: observableTypes.link, rel: rels.specialization`
> Refresh State Observable

- framework/lit/HypermediaStateMixin.js
- helper/deepCopy.js
- state/HypermediaState.js
Fixed in this PR:
- Deep Copy didn't work for dates. Now it does.
New Features:
- Before we make a state, we can wait for other attributes to be given a value. This is useful when you need to setup observables that require non-static properties.
- You can now pass custom properties at addObservable stage. This is useful if you have a more complex custom observable and the output might change based on some of these options.
> feat: A couple of small but neat updates

- state/observable/sirenObservableFactory.js
Basically, we were priming things that shouldn't be primed!
> fix: Sending token when it isn't required

- state/observable/SirenSubEntities.js
fix for, "a bug where Quiz Sections appear to be getting out of order when they are created using the Save&Copy or Save&New FACE Quiz workflow. Looking at the collections api response, you can see that the incoming data is in ascending order by id [220, 221, 222, 223]. But when I log this.items in d2l-activity-collection-editor-quiz, the order is [223, 220, 221, 222]."
> fix: Entities were added out of order.

- state/HypermediaState.js
- state/observable/SirenLink.js
- state/observable/SirenSubEntities.js
- state/observable/SirenSubEntity.js
This is a defect:https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F518693719340
It shows up using this branch: https://github.com/Brightspace/quiz-components/tree/US124788/state_push_fix
The issue is we want to call push on the parent and for it to look at all of it children. But right now the children are subentities and well, that wasn't supported / didn't work. This is to fix that problem.
I've been testing this since last Friday on my local instance and has been working!
> fix: we haven't been paying attention to subentities relationships. 

- framework/lit/HypermediaStateMixin.js
- state/Fetchable.js
- state/HypermediaState.js
- state/observable/Routable.js
- state/observable/SirenFacade.js
- state/observable/SirenLink.js
- state/observable/SirenSubEntities.js
- state/observable/SirenSubEntity.js
- state/observable/SirenSummonAction.js
- state/observable/sirenObservableFactory.js
- test/observable/sirenSubEntities.test.js
- test/state/HypermediaState.test.js
- Update method in sirensummon actions
- Always include method as a primary property
- We want to be able to send extra parameters around in routable
- fetchable, construct href when fetching if there are paramsObjs
- Fix up addObservables to include the correct properties.
- SubEntities returning full facades if only getting href
- NoFollow isn't a think for summon actions.
> fix: SummonAction are Routable and Subentities return full facades

- state/observable/Routable.js
When adding a new observer with a routed state to an observer that already fetched it `routedState` then add the new observer to the `routedState`
> fix: Routing when already fetched

- state/Fetchable.js
- state/observable/SirenAction.js
Basically, we were not handling action GET fields properly. This fixes that issue. We now sub in defaults correctly and allow one to modify them. SO yay!
> fix: up actions fields.

- state/observable/SirenSummonAction.js
- test/example-components/component-integration.test.js
- test/example-components/summon-action-components.js
Adds a `bypassCache` boolean argument to the `summonAction.summon()` function. 
Also adds two tests to confirm that the cached/bypassed calls are caching and bypassing as expected.
I also tested this manually by linking up with the summon action for the [Enrollment Rule match count mixin](https://github.com/BrightspaceHypermediaComponents/foundation-components/blob/5b1a0e01759305ff8937fe34455a265c40fff430/features/discover/mixins/match-count-mixin.js#L28) and reviewing the behavior when the argument is set/unset. This PR is needed to prevent it from caching the first returned count value.
> feat: Add bypassCache and tests to summon action
